name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Commit any pending changes
        run: |
          git add .
          git diff-index --quiet HEAD || (git commit -m "chore: auto-commit before build" && git push origin main)

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          git rm -rf .
          git checkout main -- index.html assets/*
          git add .
          git commit -m "Deploy: Updated site with latest changes"
          git push -f origin gh-pages
          git checkout main
